name: ffmpeg_kit_flutter
description: FFmpeg Kit for Flutter with updated Android bindings. Supports Android, iOS and macOS platforms.
repository: https://github.com/arthenica/ffmpeg-kit
issue_tracker: https://github.com/arthenica/ffmpeg-kit/issues
homepage: https://github.com/arthenica/ffmpeg-kit
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.ffmpegkit.flutter
        pluginClass: FFmpegKitFlutterPlugin
      ios:
        pluginClass: FFmpegKitFlutterPlugin
      macos:
        pluginClass: FFmpegKitFlutterPlugin

dependencies:
  ffmpeg_kit_flutter_platform_interface: ^0.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
